# Generated by Django 4.0.4 on 2022-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['uuid']},
        ),
    ]
